### ISSUE TITLE
 No version of 'puppetlabs-dsc' can satisfy all dependencies

### ISSUE THREAD

**Issue by kenazk** [puppetlabs/puppetlabs-dsc#113]
I'm new to using Puppet. I'm trying to install this module and I get the following error (on 3.4.3):

Error: Could not install module 'puppetlabs-dsc' (???)
  No version of 'puppetlabs-dsc' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module

Both my puppetlabs-stdlib and puppetlabs-powershell are on latest version. Anything I might be missing?

**Comment by ferventcoder** [comment]
@kenazk can you file an issue on tickets.puppetlabs.com please? Thanks!

**Comment by kenazk** [comment]
Sounds good, thanks!

**Comment by ferventcoder** [comment]
@kenazk once you file the issue, please let me know the url so I can get in and triage the ticket

**Comment by kenazk** [comment]
@ferventcoder Thanks for following up Rob. It looks like my version of Puppet Enterprise was incorrect. My PE is version 3.2.3 and Puppet version 3.4.3 which is unsupported for this module. No ticket required.

**Comment by ferventcoder** [comment]
@kenazk Ah right on, thanks for following up!
