### ISSUE TITLE
Review CheckRestrictedLanguage default arguments in ReadEnvironmentFile

### ISSUE THREAD

**Issue by kmarquette** [puppetlabs/puppetlabs-dsc#138]
In puppetlabs-dsc/build/vendor/wmf_dsc_resources/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1 function ReadEnvironmentFile line 3674

CheckRestrictedLanguage is used with $null values to check a scriptblock before executing it. This will allow all default commands in that scriptblock. I just wanted to make sure this was the intention because it is non-intuitive. If you wanted to exclude all Powershell commands, you would have to use an empty list of strings. [string[]]@() instead of a $null. 

See the comment about AllowedVariables: https://msdn.microsoft.com/en-us/library/system.management.automation.scriptblock.checkrestrictedlanguage(v=vs.85).aspx because it applies to the AllowedCommands too.

**Comment by ferventcoder** [comment]
@kmarquette Hello! Would you mind filing an issue at https://tickets.puppetlabs.com/browse/MODULES? We don't track issues here (we'll be shutting off the issues section once we've addressed another open issue's comments).

**Comment by ferventcoder** [comment]
Thanks!
