### ISSUE TITLE
it is failing through proxy 

### ISSUE THREAD

**Issue by riponbanik** [puppetlabs/puppetlabs-dsc#160]
The following is the error message. How to make it work through proxy. I have http_proxy_host and http_proxy_port in puppet config but it does not work

PS C:\ProgramData\PuppetLabs\puppet\manifests> puppet apply .\fourthcoffee.pp
Warning: Config file C:/ProgramData/PuppetLabs/puppet/etc/hiera.yaml not found, using Hiera defaults
Notice: Compiled catalog for rbwindev004.aap.pwcinternal.com in environment production in 0.22 seconds
Notice: /Stage[main]/Fourthcoffee/Dsc_xwebsite[Stop DefaultSite]/ensure: created
Error: PowerShell DSC resource MSFT_xRemoteFile  failed to execute Set-TargetResource functionality with error message: Invoking web request failed with error :
Error: /Stage[main]/Fourthcoffee/Dsc_xremotefile[Download WebContent Zip]/ensure: change from absent to present failed: PowerShell DSC resource MSFT_xRemoteFile  failed to execute Set-T
Notice: /Stage[main]/Fourthcoffee/Dsc_archive[Unzip and Copy the WebContent]: Dependency Dsc_xremotefile[Download WebContent Zip] has failures: true
Warning: /Stage[main]/Fourthcoffee/Dsc_archive[Unzip and Copy the WebContent]: Skipping because of failed dependencies
Notice: /Stage[main]/Fourthcoffee/Dsc_xwebsite[BackeryWebSite]: Dependency Dsc_xremotefile[Download WebContent Zip] has failures: true

**Comment by jpogran** [comment]
The error is occurring in the xRemoteFile DSC Resource, not in Puppet:

>Error: PowerShell DSC resource MSFT_xRemoteFile failed to execute Set-TargetResource functionality with error message: Invoking web request failed with error

The `xRemoteFile` DSC Resource is a wrapper around the `Invoke-WebRequest` cmdlet. `Invoke-WebRequest` does provide parameters to handle proxy details, however `xRemoteFile` does not expose parameters itself that uses them. A possible option is to open a feature request in the official Microsoft DSC Resource [repo](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues) or fork their implementation and use it here.

**Comment by Iristyle** [comment]
Agreed that this is something we can't address with Puppet - thanks for the report though, and good luck with getting this addressed upstream!
