### ISSUE TITLE
Hitting  PowerShell DSC resource timeout

### ISSUE THREAD

**Issue by philipwigg** [puppetlabs/puppetlabs-dsc#185]
We're receiving
```"/Stage[main]/Profile::Win_iis/Dsc_windowsfeature[install_iis]/ensure: change from absent to present failed: Catastrophic failure: PowerShell DSC resource timeout (300000 ms) exceeded while executing"``` 

when we trying to install IIS with all the sub-features.

Our manifest looks like:-
```
  dsc_windowsfeature { 'install_iis':
    dsc_ensure               => 'present',
    dsc_name                 => 'Web-Server',
    dsc_includeallsubfeature => 'True',
  }
```

I think we can probably just remove the sub-features and install the ones we really need individually... but is there any way to increase the timeout?

**Comment by Iristyle** [comment]
Thanks for the feedback @philipwigg  - we've previously discussed this internally and it's something we will be doing in the future.

Please follow https://tickets.puppetlabs.com/browse/MODULES-3180 for updates.  I'm going to close this GH issue in favor of our JIRA ticket.


Thanks!
