### ISSUE TITLE
Powershell -Sta is not available on Nano Server

### ISSUE THREAD

**Issue by alexpilotti** [puppetlabs/puppetlabs-dsc#197]
-Sta Powershell command line option is not available on Nano Server:

https://github.com/puppetlabs/puppetlabs-dsc/blob/ed55b0a17be855ec3b236f8962f98b1fc3168736/lib/puppet/provider/base_dsc/powershell.rb#L58

**Comment by Iristyle** [comment]
Thanks - this one should be easy enough to adjust.

**Comment by Iristyle** [comment]
PR #199 should address this
