### ISSUE TITLE
WaitOne does not have 2 args on Nano Server

### ISSUE THREAD

**Issue by alexpilotti** [puppetlabs/puppetlabs-dsc#198]
Nano Server uses the CoreCLR, where the WaitOne method used in the following call does not have an overload with two arguments. 

https://github.com/puppetlabs/puppetlabs-dsc/blob/ed55b0a17be855ec3b236f8962f98b1fc3168736/lib/puppet_x/puppetlabs/powershell_manager.rb#L52

**Comment by Iristyle** [comment]
CoreCLR source code for reference - https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/mscorlib/src/System/Threading/WaitHandle.cs#L178-L219

**Comment by alexpilotti** [comment]
Reflection on Nano TP5:
```
([System.Threading.WaitHandle].GetMethods()` |? Name -eq "WaitOne") | foreach { "$_"}

Boolean WaitOne()
Boolean WaitOne(Int32)
Boolean WaitOne(System.TimeSpan)
```

**Comment by Iristyle** [comment]
PR #199 should address this
