### ISSUE TITLE
Check in generated types/providers

### ISSUE THREAD

**Issue by ferventcoder** [puppetlabs/puppetlabs-dsc#2]
Otherwise it is impossible to use this module from github with r10k or librarian-puppet.

**Comment by ferventcoder** [comment]
While these things are generated, we are generating code for the module and the BUILD bits won't be run as often so we should optimize for the module users. Perhaps have a message on the generated types though so folks won't try to submit PRs against those.

**Comment by Iristyle** [comment]
Done
