### ISSUE TITLE
dsc_xadgroup resource does not appear to be idempotent

### ISSUE THREAD

**Issue by davnport** [puppetlabs/puppetlabs-dsc#200]
Hi,

The dsc_xadgroup resource does not appear to be idempotent. I updated my puppetfile to pull in the master branch and ran a test using the code below. On the first pass the group is created; subsequent runs generate `Error: The specified group already exists.`

Here is the error and the code used. 

![image](https://cloud.githubusercontent.com/assets/16022510/15197294/706eb118-1785-11e6-9ec2-6b374ad70bab.png)

```
mod 'dsc',
  :git => 'https://github.com/puppetlabs/puppetlabs-dsc',
  :ref => 'master'
```

```
class profile::windows::dsc_createad {

  $create_adgroup=hiera('create_adgroup')

  # Create an ADgroup
  dsc_xadgroup {'LSA-DSC-TESTING':
    dsc_ensure           => 'Present',
    dsc_groupname        => 'LSA-DSC-TESTING',
    dsc_category         => 'Security',
    dsc_groupscope       => 'Global',
    dsc_path             => <OU removed>,
    dsc_description      => "<puppet managed> ${::hostname} Users",
    dsc_domaincontroller => <dc removed>,
    dsc_credential       => {
      'user'     => <user removed>,
      'password' => "${create_adgroup}"
    }
  }
}
```

**Comment by jpogran** [comment]
@davnport Thanks for reporting this. I'll be looking into this as soon as I get an test AD setup to reproduce this. Would you mind filing an issue at https://tickets.puppetlabs.com/browse/MODULES with a copy paste of what you have here? We don't track issues here and will be shutting the issue section down soon. I'll update the jira ticket with my progress once thats created.

**Comment by jpogran** [comment]
Does https://github.com/PowerShell/xActiveDirectory/issues/90 apply to your issue?

**Comment by davnport** [comment]
@jpogran Thank you for the link to formal ticketing system; rookie mistake on my part. 
https://tickets.puppetlabs.com/browse/MODULES-3365

The error message in the linked ticket is similar but the circumstances appear to be different. I am only trying to create a group, I have not made it to the point of adding users or computers as my first test did not pass.

**Comment by ferventcoder** [comment]
Now that we have that over there, let's move forward with closing this ticket.
