### ISSUE TITLE
xIPAddress is missing defaultgateway parameter.

### ISSUE THREAD

**Issue by TigerScript** [puppetlabs/puppetlabs-dsc#212]
I am attempting to use the xIPAddress resource and it seems to be missing the defaultgateway parameter. This makes it pretty useless for setting static IP addresses.

**Comment by glennsarti** [comment]
Thanks for reporting an issue.

You are correct, the xIPAddress does not have a default gateway parameter.  Instead, there is a xDefaultGatewayAddress DSC Resource for that.

https://github.com/PowerShell/xNetworking#xdefaultgatewayaddress

**Comment by TigerScript** [comment]
Understood and thank you for pointing that out... However the lasest DSC resource includes this a parameter. Could this be updated to reflect this?

Best regards,
Tony.

**Comment by glennsarti** [comment]
Hi Tony,

Can you share the link to where this information is?

I looked at both the dev and master for the xIPAddress DSC resources and there's no mention of a default gateway paramter.

master
https://github.com/PowerShell/xNetworking/blob/master/DSCResources/MSFT_xIPAddress/MSFT_xIPAddress.schema.mof

dev
https://github.com/PowerShell/xNetworking/blob/dev/DSCResources/MSFT_xIPAddress/MSFT_xIPAddress.schema.mof

**Comment by TigerScript** [comment]
It looks like it was put in, and then removed in a later release. Apologies, I was looking at v2.1.1.0, its definitely not in the latest release.

**Comment by TigerScript** [comment]
https://github.com/PowerShell/xNetworking/releases/tag/2.1.1.1-PSGallery

Its in this one. My bad, should have checked most recent version.

**Comment by glennsarti** [comment]
Ahh ok, yes now I see it.  Makes sense as the default gateway is a part of the routing table, not the interface.  Are you happy for me to close this issue?

**Comment by ferventcoder** [comment]
Looks like this was resolved. Closing this issue. Please feel free to comment if this still needs to stay open. Thanks!
