### ISSUE TITLE
xRemoteDesktopSessionHost dsc resource failing with not recognized cmdlet errors

### ISSUE THREAD

**Issue by ripclawffb** [puppetlabs/puppetlabs-dsc#216]
I tried to utilize the xRemoteDesktopSessionHost dsc resource, but when I apply it via Puppet, I get  the following error:

![image](https://cloud.githubusercontent.com/assets/20031994/16672713/c2c07b5a-445c-11e6-8690-67632b31690e.png)

I was using the puppetlabs-dsc module with commit id 72a7388051a16d17495117276a7f16137c25aca3. I noticed this module had changed on 5/31/16 with commit id 4eb9cb1dc188bda7a695a737af99956ecdda64c1.

I reverted to a commit prior to that (a19c20e74202a2406ab5fe52e02b9437ad3facf7) and the issue was resolved.

**Comment by glennsarti** [comment]
Hi @ripclawffb, I did some digging around and the DSC Remote Desktop resource has changed from v1.1 to v1.2 and has added that new function call.  If you are a PE customer can contact support, if not can you please create a ticket.  The link is in https://github.com/puppetlabs/puppetlabs-dsc/blob/master/CONTRIBUTING.md

**Comment by ripclawffb** [comment]
Ok, I'll open a ticket with support.

**Comment by glennsarti** [comment]
Thanks.  I've confirmed that we now have an support ticket (20023) I'll close this github issue.
