### ISSUE TITLE
Resource installed with Package cannot be removed and deployment fails

### ISSUE THREAD

**Issue by kfrajtak** [puppetlabs/puppetlabs-dsc#229]
Hi,
in my DSC configuration, I'm trying to install vs2015agents

```
Package Vs2015Agents
  {
    Name = "vs2015agents"
    Path = "http://download.microsoft.com/download/8/A/F/8AFFDD5A-53D9-46EB-98D7-B61BBCAF0DE6/vstf_testagent.exe"
    Arguments = "/Silent /NoRestart /Log vs2015agents.log"
    ProductId = '373573FA-CEA5-37FC-BDE7-E8A0041994D9'
  }
```

This fails when the DSC extension tries to remove the downloaded file (see [line 177](
https://github.com/puppetlabs/puppetlabs-dsc/blob/master/build/vendor/wmf_dsc_resources/PSDesiredStateConfiguration/DSCResources/MSFT_PackageResource/MSFT_PackageResource.psm1#L777) in the source file) with the following message

```
VERBOSE: [2016-08-16T12:41:45] [ERROR] PowerShell DSC resource MSFT_PackageResource failed to execute Set-TargetResource functionality with error message: 
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 
Cannot remove item C:\ProgramData\Microsoft\Windows\PowerShell\Configuration\BuiltinProvCache\MSFT_PackageResource\vstf_testagent.exe: 
Access to the path 'C:\ProgramData\Microsoft\Windows\PowerShell\Configuration\BuiltinProvCache\MSFT_PackageResource\vstf_testagent.exe' is denied. 
```

Although the package was successfully installed, the deployment failed. Another deployment attempt succeeds since the package has been already installed.

Is there a workaround to this issue?

Thanks for help,
Karel

**Comment by ferventcoder** [comment]
@kfrajtak this repository is for dsc resources run through Puppet. You may be looking for https://github.com/PowerShell/DscResources. Please feel free to comment and/or reopen this ticket if you are seeing issues with Puppet+DSC. Thanks!

**Comment by kfrajtak** [comment]
Ah! Sorry, thanks for pointing me to the right repository.

**Comment by ferventcoder** [comment]
No worries.

**Comment by ferventcoder** [comment]
I'd suggest looking at Chocolatey as well if you are serious about software management on Windows. DSC has cChoco resource and it's quite comprehensive. https://chocolatey.org/ (if you haven't heard of it or are not aware of all of its capabilities - e.g. works completely offline and is super business friendly) - https://chocolatey.org/docs/features-infrastructure-automation#powershell-dsc
