### ISSUE TITLE
'puppetlabs-dsc' (v1.0.1) requires 'puppetlabs-powershell' (>= 1.0.1 < 2.0.0)

### ISSUE THREAD

**Issue by marcinbojko** [puppetlabs/puppetlabs-dsc#234]
'puppetlabs-dsc' (v1.0.1) requires 'puppetlabs-powershell' (>= 1.0.1 < 2.0.0)

but 

puppetlabs-powershell (v2.0.2)  invalid

**Comment by MosesMendoza** [comment]
Hi @marcinbojko - thanks for reaching out. puppetlabs-powershell (2.x) was released after puppetlabs-dsc (1.0.1), and the puppetlabs-dsc dependency on powershell (>= 1.0.1 < 2.0.0) was likely conservative dependency expression to prevent accidental breakage by pulling down the powershell 2.x. puppetlabs-dsc (1.1.0) was updated to express dependency on puppetlabs-powershell (>= 1.0.1 < 3.0.0). Any chance you can use puppetlabs-dsc 1.1.0?

**Comment by ferventcoder** [comment]
We've released dsc 1.1.0 to address this.

**Comment by ferventcoder** [comment]
Sorry, closed as we've addressed this issue already and released a version of dsc that allows for this scenario. If you feel that this is still an issue, please let us know.
