### ISSUE TITLE
DSC module fails to run because of previous process stucked

### ISSUE THREAD

**Issue by vzabauski** [puppetlabs/puppetlabs-dsc#235]
I'm getting the following problem when I'm running Puppet agent.

```
PS C:\Users\Administrator> puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for stgwatchern2
Info: Applying configuration version '1473404009'
Error: /Stage[main]/Scomagent/Dsc_file[DscFolder]: Could not evaluate: Cannot invoke the Invoke-DscResource cmdlet. The
Invoke-DscResource cmdlet is in progress and must return before Invoke-DscResource can be invoked. Use -Force option if
that is available to cancel the current operation.
Notice: /Stage[main]/Scomagent/Dsc_windowsfeature[NETFramework35]: Dependency Dsc_file[DscFolder] has failures: true
Warning: /Stage[main]/Scomagent/Dsc_windowsfeature[NETFramework35]: Skipping because of failed dependencies
Notice: /Stage[main]/Scomagent/Dsc_xremotefile[ScomAgentInstaller]: Dependency Dsc_file[DscFolder] has failures: true
Warning: /Stage[main]/Scomagent/Dsc_xremotefile[ScomAgentInstaller]: Skipping because of failed dependencies
Notice: /Stage[main]/Scomagent/Dsc_archive[UnzipScomAgentInstaller]: Dependency Dsc_file[DscFolder] has failures: true
Warning: /Stage[main]/Scomagent/Dsc_archive[UnzipScomAgentInstaller]: Skipping because of failed dependencies
Notice: /Stage[main]/Scomagent/Dsc_package[ScomAgent]: Dependency Dsc_file[DscFolder] has failures: true
Warning: /Stage[main]/Scomagent/Dsc_package[ScomAgent]: Skipping because of failed dependencies
Notice: Applied catalog in 3.77 seconds
```

Also I've noticed sometimes puppet agent leaves lock file after deployment fails. I had to remove it manually after reboot.

Here's my  init file.
[init.txt](https://github.com/puppetlabs/puppetlabs-dsc/files/463362/init.txt)

I'm using the latest version of Puppet open source on CentOS 7.

**Comment by ferventcoder** [comment]
@vzabauski please provide a puppet agent run or apply from the Windows system you are seeing this on with `--debug --verbose --trace`.

We'll also need to understand the version of Windows and the version of Puppet (please tell us the version from `puppet -V`).

**Comment by vzabauski** [comment]
I'm running it on Windows Server 2012, `puppet -V` gives me 4.5.3 version.
The problem was occurring when I was running **dsc_package** resource with some invalid arguments. Windows installer wasn't terminating though log was full of errors, so msiexec process kept spinning in background for eternity. I had to terminate puppet manually but when I was doing it, it just left dsc working, without stopping it. That's the problem. The solution is just to stop **msiexec** and all the **wmi** processes manually. This happens because of Powershell DSC behavior, not Puppet DSC module, so I think we can close this issue. Thanks for paying attention to it.

**Comment by ferventcoder** [comment]
No worries, and we always ask about version of Puppet because "latest version" currently is 4.6.2.
