### ISSUE TITLE
Inconsequence in dsc_windowsoptionalfeature

### ISSUE THREAD

**Issue by marcinbojko** [puppetlabs/puppetlabs-dsc#238]
1. Description

MS defnes resource [https://msdn.microsoft.com/en-us/powershell/dsc/windowsoptionalfeatureresource](url) in scheme:

```
WindowsOptionalFeature [string] #ResourceName
{
    Name = [string]
    [ Ensure = [string] { Absent | Present }  ]
    [ Source = [string] ]
    [ NoWindowsUpdateCheck = [bool] ]
    [ RemoveFilesOnDisable = [bool] ]
    [ LogLevel = [string] { ErrorsOnly | ErrorsAndWarning | ErrorsAndWarningAndInformation }  ]
    [ LogPath = [string] ]
    [ DependsOn = [string[]] ]
```

In puppet-dsc scheme [https://github.com/puppetlabs/puppetlabs-dsc/blob/master/build/vendor/wmf_dsc_resources/PSDesiredStateConfiguration/DSCResources/MSFT_WindowsOptionalFeature/MSFT_WindowsOptionalFeature.schema.mof](url) we got

```
{
    [Key] String Name;
    [Write, ValueMap{"Enable","Disable"}, Values{"Enable","Disable"}] String Ensure;
    [Write] String Source[];
    [Write] Boolean NoWindowsUpdateCheck;
    [Write] Boolean RemoveFilesOnDisable;
    [Write, ValueMap{"ErrorsOnly","ErrorsAndWarning","ErrorsAndWarningAndInformation"}, Values{"ErrorsOnly","ErrorsAndWarning","ErrorsAndWarningAndInformation"}] String LogLevel;
    [Write] String LogPath;
    [Read] String CustomProperties[];
    [Read] String Description;
    [Read] String DisplayName;
};
```

In parametr dsc_ensure we should use Absent|Present not Enable|Disable according to a MS scheme.
Using it via class it generates notify:

Notice: /Stage[main]/xxx/Dsc_windowsoptionalfeature[SimpleTCP]/ensure: ensure changed 'present' to 'enable'

Trying to use Present|Absent we end with an error.
1. Expected behaviour
   Use Present|Absent

**Comment by jpogran** [comment]
@marcinbojko We build the Puppet types based off the released MOF schema Microsoft publishes. If we check both the current WMF 5.0 and beta WMF 5.1, both show the following:

```
PS C:\Users\Administrator> Get-DscResource -Name windowsoptionalfeature -Syntax
WindowsOptionalFeature [String] #ResourceName
{
    Name = [string]
    [DependsOn = [string[]]]
    [Ensure = [string]{ Disable | Enable }]
    [LogLevel = [string]{ ErrorsAndWarning | ErrorsAndWarningAndInformation | ErrorsOnly }]
    [LogPath = [string]]
    [NoWindowsUpdateCheck = [bool]]
    [PsDscRunAsCredential = [PSCredential]]
    [RemoveFilesOnDisable = [bool]]
    [Source = [string[]]]
}

PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

It appears that the documentation site has been either updated prematurely and they haven't yet released a breaking change in parameter values, or they plan to make a breaking change in parameter values at some point and it hasn't yet reached a release build. When it does get released we can rebuild the types and make a new release

**Comment by ferventcoder** [comment]
Sweet!

**Comment by ferventcoder** [comment]
You may be specifying `ensure => present`, do you get the same errors with `ensure => enable`?

**Comment by marcinbojko** [comment]
Tested with:
ensure: enable
dsc_ensure: enable
dsc_ensure: present.

Only 'present' is giving me:

`Error: Failed to apply catalog: Parameter dsc_ensure failed on Dsc_windowsoptionalfeature[SimpleTCP]: Parameter ensure failed on Dsc_windowsoptionalfeature[SimpleTCP]: Invalid value "present". Valid values are exists?, enable, disable.  at /etc/puppetlabs/code/environments/production/modules/win_manage/manifests/init.pp:134 at /etc/puppetlabs/code/environments/production/modules/win_manage/manifests/init.pp:134`

**Comment by jpogran** [comment]
Closing this out, as there is nothing we can do at this point. Updated types and parameters will come as the DSC Resources are released
