### ISSUE TITLE
issue in v1.1.0: "A parameter cannot be found that matches parameter name 'f'. "

### ISSUE THREAD

**Issue by mansong1** [puppetlabs/puppetlabs-dsc#239]
During a puppet run the following error occurs:

**_Could not evaluate: A parameter cannot be found that matches parameter name 'f'. Source: .../Dsc_xiismodule[PHP54]_** 

This is the resource I'm using:

  dsc_xIISModule { 'PHP54':
    dsc_ensure      =>'Present',
    dsc_verb        => '*',
    dsc_moduletype  =>'FastCgiModule',
    dsc_requestpath =>'*.php',
    dsc_name        =>'PHP-5.4',
    dsc_path        =>'C:\PHP-5.4\php-cgi.exe',
  }

This works fine in v1.0.1.

**Comment by jpogran** [comment]
@mansong1 I don't receive the same error using your example, it parses fine. I get the following:

```
Error: /Stage[main]/Main/Dsc_xiismodule[PHP54]: Could not evaluate: PowerShell DSC resource MSFT_xIisModule  failed to execute Test-TargetResource functionality with error message: Cannot bind argument to parameter 'Verb' because it is an empty string.
```

A parameter error like this happens before DSC is called, and indicates that an incorrect parameter was specified in the puppet manifest. If you run the manifest with `puppet apply --debug` in an interactive session on the target host that will give you more information. You may be able to find the line that has the incorrect parameter added.

**Comment by mansong1** [comment]
@jpogran I've amended the resource I was using. The attribute dsc_verb should be an asterisk rather than empty string. That should get rid of the error you got. 

I've dug a bit further and found the errors I was getting was to due to some errors in the MSFT_xIisModule.psm1.  I've created a pull request for the file on Microsofts Powershell repository:

https://github.com/PowerShell/xWebAdministration/pull/240

**Comment by MColaianni** [comment]
I have the same issue. I temporarily corrected it by downgrading xWebAdministration to the previous release version.

**Comment by jpogran** [comment]
@mansong1 nice investigative work! When that PR get's merged and they release a new tag, we can add it to our release

**Comment by Iristyle** [comment]
@mansong1 / @MColaianni - now that 1.2.0 has shipped with a newer xWebAdministration, could you confirm that this is no longer a problem?


Thanks!

**Comment by mansong1** [comment]
Yes.

**Comment by jpogran** [comment]
Glad to hear it. I'll close this out then
