### ISSUE TITLE
WMF 5.1 breaking puppetlabs-dsc v1.1.0?

### ISSUE THREAD

**Issue by freni59** [puppetlabs/puppetlabs-dsc#240]
Hi guys,

Sad to report that when I'm evaluating Windows Server 2016 which ships with WMF 5.1 my Puppet agent run seems to hang indefinently. I've done some further testing and reproduced the behaviour on Server 2012 R2 when installing the WMF 5.1 preview. BUT when using Windows Server 2016 CTP5 I had no problem of this sort, but as I vaguely remember that also had a build of WMF 5.1 in it.
So what I am doing in my manifest is this:
    dsc_environment {'RubyPath':
      dsc_name   => 'PATH',
      dsc_value  => 'C:\Program Files\Puppet Labs\Puppet\sys\ruby\bin',
      dsc_path   => true,
      dsc_ensure => 'present',
    }
I've attached the verbose+debug output that seems relevant. I've also seen the behaviour using a dsc_windowsfeature resource. The above is from our production environment running on ~100 Server 2008R2 -> 2012R2. If not broken of with a ctrl+c it will wait indefinetly. And repeat the: Debug: Waited 50 milliseconds... until the end of time.

[Puppet_Dsc_verboseoutput.txt](https://github.com/puppetlabs/puppetlabs-dsc/files/507920/Puppet_Dsc_verboseoutput.txt)

**Comment by jpogran** [comment]
Hi @freni59, this is a known issue in the underlying code we use to control the PowerShell process. We've been working on a different approach in [MODULES-3690](https://tickets.puppetlabs.com/browse/MODULES-3690) which will resolve this issue. We hope to have the fix out really soon.

**Comment by freni59** [comment]
@jpogran great to hear, thought you were allready on the case :-)

**Comment by MikaelSmith** [comment]
I'm trying to apply a dsc file resource using puppetlabs-powershell#stable and puppetlabs-dsc#master, and still encounter issues a similar issue: https://gist.github.com/MikaelSmith/4eb55e2672f48f58ad74e5f064b9ff67.

Is the solution for MODULES-3690 being tested with dsc?

**Comment by ferventcoder** [comment]
@MikaelSmith eventually yes.

**Comment by Iristyle** [comment]
Version 1.2.0 of the module has shipped containing this fix.  Closing this issue as a result.

**Comment by marcinbojko** [comment]
I would like to reopen this issue - with:
puppetlabs-dsc (v1.2.0)
puppetlabs-powershell (v2.1.0)
tested on WIndows 10 Pro, version 1607, Powershell as enclosed:

Name                           Value
----                           -----
PSVersion                      5.1.14393.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

issues pointed out by @MikaelSmith are still present. So at least on Windows 10 Pro Anniversary Edition I am unable to run Powershell DSC.

```
Debug: 2016-11-19 07:43:23 +0100 C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe -NoProfile -NonInteractive -NoLogo -ExecutionPolicy Bypass -Command - is running as pid: 5392
Debug: Waited 50 milliseconds...
Debug: Waited 50 milliseconds...
Debug: Waited 50 milliseconds...
Debug: Waited 50 milliseconds...
Debug: Waited 50 milliseconds...
Debug: 2016-11-19 07:43:23 +0100 STDOUT> At line:1 char:32

Debug: 2016-11-19 07:43:23 +0100 STDOUT> +         if ($runspace -eq $null)

Debug: 2016-11-19 07:43:23 +0100 STDOUT> +                                ~

Debug: 2016-11-19 07:43:23 +0100 STDOUT> Missing statement block after if ( condition ).

Debug: 2016-11-19 07:43:23 +0100 STDOUT>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException

Debug: 2016-11-19 07:43:23 +0100 STDOUT>     + FullyQualifiedErrorId : MissingStatementBlock

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

Debug: 2016-11-19 07:43:23 +0100 STDOUT>           $runspace = [RunspaceFactory]::CreateRunspace()

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

Debug: 2016-11-19 07:43:23 +0100 STDOUT>           $runspace.Open()

Debug: 2016-11-19 07:43:23 +0100 STDOUT>

```
