### ISSUE TITLE
When module is installed on Puppet 3.8.x, Linux agents in the infrastructure are trying to incorrectly modify resources from the module.

### ISSUE THREAD

**Issue by ryancfields** [puppetlabs/puppetlabs-dsc#252]
When this module is installed in Puppet 3.8.2, we are seeing linux hosts loop on trying to apply File resources.   No references exist to actually use this module in our manifests for any Windows or Linux agent.  Just having the module installed causes this behavior.  

So far I only see this on CentOS 7.x agents.  

The behavior is the agents will stick in an infinite loop:

Debug: /File[/var/opt/lib/pe-puppet/lib/puppet_x/dsc_resources/xExchange/DSCResources/MSFT_xExchImapSettings/MSFT_xExchImapSettings.psm1]: The container /var/opt/lib/pe-puppet/lib will propagate my refresh event
Debug: Using cached connection for https://puppet.contoso.com:8140
Debug: Caching connection for https://puppet.contoso.com:8140
Notice: /File[/var/opt/lib/pe-puppet/lib/puppet_x/dsc_resources/xExchange/DSCResources/MSFT_xExchImapSettings/MSFT_xExchImapSettings.schema.mof]/ensure: defined content as '{md5}
6492e19a3d4c6837e4d2f5a98a728323'
Debug: /File[/var/opt/lib/pe-puppet/lib/puppet_x/dsc_resources/xExchange/DSCResources/MSFT_xExchImapSettings/MSFT_xExchImapSettings.schema.mof]: The container /var/opt/lib/pe-puppet/lib will propagate my refresh event
Debug: Using cached connection for https://puppet.contoso.com:8140
Debug: Caching connection for https://puppet.contoso.com:8140

**Comment by jpogran** [comment]
Hi @ryancfields, this looks more like a modulesync issue than a dsc module issue. All modules are synced by default to agents, regardless of whether its a 'windows' module or not, so you will see the files being copied to nodes regardless of OS (that is, unless you setup environments). 

Could you open up a bug in https://tickets.puppetlabs.com and reply back here with the number? I can help route it to someone who can help diagnose it. If you are a PE customer, please don't hesitate to reach out there and they will expedite.

**Comment by ryancfields** [comment]
Hi James,

I opened a request for the issue:
http://support.puppet.com/hc/requests/21963

**Comment by jpogran** [comment]
Thanks. I'll read up and see where I can help.

**Comment by jpogran** [comment]
@ryancfields I'm going to close this out as you've been working with Puppet Support directly
