### ISSUE TITLE
Request for better documentation examples

### ISSUE THREAD

**Issue by ricardogaspar2** [puppetlabs/puppetlabs-dsc#271]
Hi, I know that this is not the best place to do this, but I already asked a question in ask.puppet.com about this (https://ask.puppet.com/question/29547/how-to-use-dsc_script/) .
I'm trying to use dsc_script but I didn't manage to do it right, but it all comes down to the documentation.
The examples used are simple, but it would be of huge value to have examples of syntax for other dsc resources using puppet.

**Comment by jpogran** [comment]
Hi @ricardogaspar2, you raise an important point, documentation is always an important part of using software. In this case we are talking about looking for documentation about using `dsc_script` which is a wrapper on the PowerShell DSC `Script` Resource. Any documentation on how to use that resource can be found in the usual Microsoft resources like Technet, or books or online. MS does admit they need to do more documentation with DSC Resources.

The `script` resource is typically used as a 'last resort', for when there isn't already another resource available to do the task at hand. You already noted there are both Puppet modules and DSC Resources that are custom built to handle this task and make it easier. Indeed, it is notoriously hard to use the `script` resource even in the best cases, because it 'looks' like a PowerShell script but behaves like compiled code, with complicated rules about variable scope and use.

If you want to continue using the `script` resource to do this task, the best advice I can give is to reduce the moving parts and build on each part as you get it working. First make sure the inline code works, then move on to making sure the DSC part works in a simple example on a test box. Then move onto the Puppet example.

When figuring out the Puppet side, the key is 'seeing' the code that is being sent to DSC by Puppet. If that code is correct, then things are likely to work. You can see this by running Puppet interactively from the command line and using the '--debug' switch. In the debug output Puppet will display the PowerShell code it generated and sent to DSC. Copy that to your editor of choice and look to see if it is correct code. Look for common things like dollar signs not being escaped correctly or variables being interpolated when they shouldn't. Let me know what you find.

**Comment by ricardogaspar2** [comment]
Thanks for the answer!
Another one: It is only possible to use the dsc_x types mentioned in types.md right?
I would like to use other modules I installed in my machines and use puppet to called them.
E.g. dsc_xsystemvirtualmemory (https://gallery.technet.microsoft.com/scriptcenter/How-to-configure-virtual-96c32fec)

**Comment by jpogran** [comment]
What you are looking for is [Building Custom DSC Resources](https://github.com/puppetlabs/puppetlabs-dsc/blob/master/README_BUILD.md#build-custom-dsc-resource-types). It requires building the types using rake and ruby, we are actively working on making this process easier in the near future

**Comment by ricardogaspar2** [comment]
The documentation has some pitfalls. It says that it requires ruby 1.9.3, but when I try to do bundle install I get a list of dependencies that cannot be resolved. Only when I used 2.3.3 I could use bundle install.

I also got a warning with the MOF file from the xSystemVirtualMemory module saying that it may contain different line endings (LF and CRLF). I check it with notepad++ and I thing it doesn't. I also tried to use Atom with the line-ending-selector package (https://github.com/atom/line-ending-selector) to change to CRLF and after trying with this modified MOF file it gives an error. Should I stick with warning?
BTW, the files are encoded in UTF-8.

**Comment by ricardogaspar2** [comment]
I also had an error after executing rake dsc:build.
```
/code/build/dsc.rake:164:in `block (5 levels) in <top (required)>'
/code/build/dsc.rake:154:in `block (4 levels) in <top (required)>'
/code/build/dsc.rake:152:in `each'
/code/build/dsc.rake:152:in `block (3 levels) in <top (required)>'
/code/build/dsc.rake:76:in `block (3 levels) in <top (required)>'
/code/build/dsc.rake:30:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => dsc:resources:checkout
(See full trace by running task with --trace)

```

```
$ bundle exec rake dsc:build --trace
** Invoke dsc:build (first_time)
** Execute dsc:build
** Invoke dsc:resources:import (first_time)
** Execute dsc:resources:import
Downloading and Importing DSC Powershell modules files
cd /code/import/dsc_resources_tmp && git submodule update --init
** Invoke dsc:resources:checkout (first_time)
** Execute dsc:resources:checkout
Getting latest release tags for DSC resources in /code/import/dsc_resources_tmp/xDscResources...
rake aborted!
xActiveDirectory does not have any '*-PSGallery' tags. Appears it has not been released yet. Tags found %D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
%D
/code/build/dsc.rake:164:in `block (5 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
/code/build/dsc.rake:154:in `block (4 levels) in <top (required)>'
/code/build/dsc.rake:152:in `each'
/code/build/dsc.rake:152:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/code/build/dsc.rake:76:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/code/build/dsc.rake:30:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
/usr/local/rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => dsc:resources:checkout
```

**Comment by jpogran** [comment]
We require ruby 1.9.3 for the MOF parser gem, which we use to parse the DSC Resources and generate the Puppet types. This gem requires some depedent libs depending on your OS, so your installation steps may vary there. Follow the gem instructions to install the dependencies listed. This has been tested on macOS, and recently on centos.

Regarding xSystemvirtualMemory, the gem we use to parse the MOF files is very very specific in what encodings it can read. Messages like the ones you are seeing sometimes happen when a file is edited both on Windows and Linux/Mac and line endings are mixed. You don't link where you are getting xSystemvirtualMemory so I can't double check for you.

The error you paste looks to me like your git version is out of date, which may also be part of the problem above. Part of the process we are using checks out certain tag versions from the git repos, which requires a recent version of git to work correctly. Older versions show '%D' instead of the tag names. Make sure your git version is recent, mine is 2.10 at this writing.

**Comment by ricardogaspar2** [comment]
First about the xSystemVirtualMemory, I got it from here:
https://gallery.technet.microsoft.com/scriptcenter/How-to-configure-virtual-96c32fec

Second, about puppet dsc build using ruby 1.9.3:
`[rchavesg@linuxrdp-test puppetlabs-dsc]$ bundle install
Fetching https://github.com/puppetlabs/mof.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies..........................................................................................                                             ................................................................................................................                                             ................................................................................................................                                             ................................................................................................................                                             ................................................................................................................                                             ...................................................................................................
Bundler could not find compatible versions for gem "beaker":
  In Gemfile:
    beaker (>= 3)

    beaker-abs (~> 0.1) was resolved to 0.2.0, which depends on
      beaker (< 4.0, >= 2.9.0)

    beaker-module_install_helper was resolved to 0.1.2, which depends on
      beaker (>= 2.0)

    beaker-module_install_helper was resolved to 0.1.2, which depends on
      beaker (>= 2.0)

    beaker-rspec was resolved to 2.0.1, which depends on
      beaker (~> 1.3)

    master_manipulator was resolved to 1.2.6, which depends on
      beaker (>= 2.7.0)
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    beaker-rspec was resolved to 6.0.0, which depends on
      ruby (>= 2.2.5)

    pry was resolved to 0.10.4, which depends on
      coderay (~> 1.1.0) was resolved to 1.1.1, which depends on
        ruby (>= 1.8.6)

    rspec-puppet (>= 2.3.2) was resolved to 2.5.0, which depends on
      rspec was resolved to 3.5.0, which depends on
        rspec-mocks (~> 3.5.0) was resolved to 3.5.0, which depends on
          diff-lcs (< 2.0, >= 1.2.0) was resolved to 1.3, which depends on
            ruby (>= 1.8)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      google-api-client (~> 0.9) was resolved to 0.9.12, which depends on
        googleauth (~> 0.5) was resolved to 0.5.1, which depends on
          faraday (~> 0.9) was resolved to 0.11.0, which depends on
            ruby (>= 1.9)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      google-api-client (~> 0.9) was resolved to 0.9.12, which depends on
        ruby (~> 2.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      hocon (~> 1.0) was resolved to 1.2.4, which depends on
        ruby (>= 1.9.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      net-ssh (~> 3.2) was resolved to 3.2.0, which depends on
        ruby (>= 2.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      net-ssh (~> 3.2) was resolved to 3.2.0, which depends on
        ruby (>= 2.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      net-ssh (~> 3.2) was resolved to 3.2.0, which depends on
        ruby (>= 2.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      rbvmomi (~> 1.9) was resolved to 1.9.4, which depends on
        nokogiri (~> 1.5) was resolved to 1.6.8.1, which depends on
          ruby (>= 1.9.2)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      rbvmomi (~> 1.9) was resolved to 1.9.4, which depends on
        nokogiri (~> 1.5) was resolved to 1.6.8.1, which depends on
          ruby (>= 1.9.2)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      rbvmomi (~> 1.9) was resolved to 1.9.4, which depends on
        nokogiri (~> 1.5) was resolved to 1.6.8.1, which depends on
          ruby (>= 1.9.2)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      rbvmomi (~> 1.9) was resolved to 1.9.4, which depends on
        nokogiri (~> 1.5) was resolved to 1.6.8.1, which depends on
          ruby (>= 1.9.2)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      rbvmomi (~> 1.9) was resolved to 1.9.4, which depends on
        nokogiri (~> 1.5) was resolved to 1.6.8.1, which depends on
          ruby (>= 1.9.2)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      rbvmomi (~> 1.9) was resolved to 1.9.4, which depends on
        nokogiri (~> 1.5) was resolved to 1.6.8.1, which depends on
          ruby (>= 1.9.2)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

Could not find gem 'ruby (>= 2.0)', which is required by gem 'puppet', in any of the sources.
`

**Comment by jpogran** [comment]
sorry for delay in writing. try ` bundle install --without system_tests` in order to skip installing beaker. will look at the dsc resource as soon as i can

**Comment by jpogran** [comment]
Downloaded and inspected the files with sublimetext. It shows the psm1 and psd1 files as UTF16LE with a BOM, which the MOF parser cannot parse. We are looking to replace the parser with something more forgiving soon, but until then you have to re-save these files with UTF8 encoding. In sublimetext this can be done using the save menu.

**Comment by ricardogaspar2** [comment]
Hi again,
I tried with the `bundle install --without system_tests` command but it gave the same error.

So far I could only run bundler and compile types using ruby 2.3.3. But I didn't test them yet (just compiled them). With ruby 1.9.3 I couldn't get through the building process.

Regarding the xSystemVirtualMemory MOF file I used the one in another repo (https://github.com/msperrin/xSystemVirtualMemory).

**Comment by ricardogaspar2** [comment]
Quick update: Using the ruby version 2.3.3, I build the xSystemVirtualMemory type and already tested in Windows Server 2012 R2 running puppet. It worked.

**Comment by jpogran** [comment]
I can build all types with the current master of powershell/DSCResources with both ruby 1.9.3 and 2.3.1. When the build instructions were written, I don't think the 2.3 branch was out yet, so it is good we can revisit and see we can build with newer ruby versions.

I'm glad you were able to build the xSystemVirtualMemory DSC Resource, I will mark #278 as closed as well.

I have opened PR #280 to address updating documentation. Please comment there for any additional points you want covered. Its a work in progress, so not everything is updated, but it's a start
