### ISSUE TITLE
[FEATURE] More frequent releases of puppetlabs-dsc

### ISSUE THREAD

**Issue by marcinbojko** [puppetlabs/puppetlabs-dsc#272]
Hi all.
If possible, I would love to have more frequent releases of puppetlabs-dsc, including newer releases from modules. Currently we are behind schedule with at least 2 major versions, where a lots of features were added and bugs removed.
Yes, we can compile it on our own, but for majority of us this step is a really big issue that shoudn't be taken lightly.
Maybe once a month - no new features/bug fixes, only newer DSC Resources?

**Comment by jpogran** [comment]
Hi @marcinbojko thanks for the feedback, this helps us prioritize our work.

As a policy we try to stay in sync with the major DSC Resource Kit releases from Microsoft. We generally also wait a few days to ensure there aren't any hotfixs that need to be included as well. This is in sync with our supported modules policy of trying to have the most stable code released at any one point in time.

We last released on Nov 2nd, which had the [November](https://blogs.msdn.microsoft.com/powershell/2016/11/02/dsc-resource-kit-november-2016-release/) release. The [December 14th](https://blogs.msdn.microsoft.com/powershell/2016/12/14/dsc-resource-kit-release-december-2016/) release only added the `AuditPolicyDsc` resource, so we decided to wait thinking more resources would be updated soon, and soon enough on December 16th there were several more updated.  Unfortunately the holidays hit after that and we are now into the new year. While we were scheduling the release with our other module release schedules, the [January](https://blogs.msdn.microsoft.com/powershell/2017/01/25/dsc-resource-kit-release-january-2017/) release was released.

Unfortunately I can't yet comment on a date, but expect a release soon. We are also in the planning stages for making building DSC Resources into our module a much easier process. Stay tuned

**Comment by marcinbojko** [comment]
Thanks, @jpogran , as usuall you 're helpful.
But, please notice, than even if'we are talking about major DSC releases, there is stiil plenty of changes in dependend resources like (you know it much better than I am): [https://github.com/puppetlabs/puppetlabs-dsc/blob/master/types.md](url)
I would say that puppetlabs-dsc as aggregator for those resources is EXTREMLY important.

**Comment by jpogran** [comment]
We recently met and made short term goals to do a point release soon with updated resources (one ticket being https://tickets.puppetlabs.com/browse/MODULES-4371) and a longer term goal of addressing building this yourself more easily. Our progress can be tracked there, so I'm closing this issue out.
