### ISSUE TITLE
Could not find a suitable provider for dsc_windowsfeature

### ISSUE THREAD

**Issue by jwtdrjj** [puppetlabs/puppetlabs-dsc#273]
I am getting this error and I am not sure how to fix.

**Comment by jpogran** [comment]
Hi @jwtdrjj, are you sure you have the prerequisites satisfied? See here: https://github.com/puppetlabs/puppetlabs-dsc#windows-system-prerequisites

**Comment by jwtdrjj** [comment]
You can close.  I believe the issue is the WMF 5 prereq

**Comment by ferventcoder** [comment]
Also if you are running vagrant, be sure you are not running into FACT-1510. https://tickets.puppetlabs.com/browse/FACT-1510
