### ISSUE TITLE
[FEATURE] Include any NTFS/ACL setting module.

### ISSUE THREAD

**Issue by marcinbojko** [puppetlabs/puppetlabs-dsc#274]
Hi,I would like to propose including to DSC Resources modules for managing NTFS Rights on filesystems:
https://github.com/SNikalaichyk/cNtfsAccessControl

**Comment by ferventcoder** [comment]
Unfortunately the built modules are not likely to use "c" (community) DSC resources, however you can follow the instructions on rebuilding the module to include custom resources. HTH

Also curious where the puppetlabs/acl module falls down? It's quite a powerful module that can really do some very granular permissions.

**Comment by ferventcoder** [comment]
Just had a look and confirmed that the puppetlabs/acl module has more features than this, but as I mentioned, you can always build custom DSC resources if you choose. Give BUILDING a read. Thanks!

**Comment by marcinbojko** [comment]
Thanks. I'll try with puppetlabs/ACL. I just wanted to be with DSC for the whole time.

**Comment by jpogran** [comment]
Thanks for the suggestion @marcinbojko, but Puppet is unlikely to include the community resources (those with c prepended) for the same reasons as issue #272. You can always include them in your distribution, or in this case use the puppet module which covers more use cases. I am going to close this now, but feel free to open if issues arise
