### ISSUE TITLE
bundle install errors

### ISSUE THREAD

**Issue by nealpeters86** [puppetlabs/puppetlabs-dsc#278]
Hello, 

We are trying to build our custom DSC resources (cChoco). The manual states that you should use ruby 1.9.3. We currently have:

ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]

- Bundler version 1.14.4 is installed.

When we run the command bundle install we are getting the following errors.

Is there a way of working around this issue? 

[root@puppetmaster dsc]# pwd
/etc/puppetlabs/code/environments/production/modules/dsc

[root@puppetmaster dsc]# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching https://github.com/puppetlabs/mof.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Bundler could not find compatible versions for gem "beaker":
  In Gemfile:
    beaker (>= 3)

    beaker-abs (~> 0.1) was resolved to 0.2.0, which depends on
      beaker (< 4.0, >= 2.9.0)

    beaker-module_install_helper was resolved to 0.1.2, which depends on
      beaker (>= 2.0)

    beaker-module_install_helper was resolved to 0.1.2, which depends on
      beaker (>= 2.0)

    beaker-rspec was resolved to 2.0.1, which depends on
      beaker (~> 1.3)

    master_manipulator was resolved to 1.2.6, which depends on
      beaker (>= 2.7.0)
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    pry was resolved to 0.10.4, which depends on
      coderay (~> 1.1.0) was resolved to 1.1.1, which depends on
        ruby (>= 1.8.6)

    rspec-puppet (>= 2.3.2) was resolved to 2.5.0, which depends on
      rspec was resolved to 3.5.0, which depends on
        rspec-mocks (~> 3.5.0) was resolved to 3.5.0, which depends on
          diff-lcs (< 2.0, >= 1.2.0) was resolved to 1.3, which depends on
            ruby (>= 1.8)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      google-api-client (~> 0.9) was resolved to 0.10.0, which depends on
        googleauth (~> 0.5) was resolved to 0.5.1, which depends on
          faraday (~> 0.9) was resolved to 0.11.0, which depends on
            ruby (>= 1.9)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      google-api-client (~> 0.9) was resolved to 0.10.0, which depends on
        ruby (~> 2.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      net-ssh (~> 3.2) was resolved to 3.2.0, which depends on
        ruby (>= 2.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      net-ssh (~> 3.2) was resolved to 3.2.0, which depends on
        ruby (>= 2.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      net-ssh (~> 3.2) was resolved to 3.2.0, which depends on
        ruby (>= 2.0)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      rbvmomi (~> 1.9) was resolved to 1.9.4, which depends on
        nokogiri (~> 1.5) was resolved to 1.7.0.1, which depends on
          ruby (>= 2.1.0)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    rspec-puppet-facts was resolved to 1.7.1, which depends on
      puppet was resolved to 4.9.2, which depends on
        ruby (>= 1.9.3)

    puppet-blacksmith (>= 3.4.0) was resolved to 3.4.0, which depends on
      rest-client (~> 1.8.0) was resolved to 1.8.0, which depends on
        ruby (>= 1.9.2)

    puppet-blacksmith (>= 3.4.0) was resolved to 3.4.0, which depends on
      rest-client (~> 1.8.0) was resolved to 1.8.0, which depends on
        ruby (>= 1.9.2)

    puppet-blacksmith (>= 3.4.0) was resolved to 3.4.0, which depends on
      rest-client (~> 1.8.0) was resolved to 1.8.0, which depends on
        ruby (>= 1.9.2)

    puppet-blacksmith (>= 3.4.0) was resolved to 3.4.0, which depends on
      rest-client (~> 1.8.0) was resolved to 1.8.0, which depends on
        ruby (>= 1.9.2)

    puppet-blacksmith (>= 3.4.0) was resolved to 3.4.0, which depends on
      rest-client (~> 1.8.0) was resolved to 1.8.0, which depends on
        ruby (>= 1.9.2)

    beaker (>= 3) was resolved to 3.0.0, which depends on
      google-api-client (~> 0.9) was resolved to 0.10.0, which depends on
        retriable (< 4.0, >= 2.0) was resolved to 3.0.0, which depends on
          ruby (>= 2.0.0)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

    pry was resolved to 0.10.4, which depends on
      slop (~> 3.4) was resolved to 3.6.0, which depends on
        ruby (>= 1.8.7)

Could not find gem 'ruby (>= 2.0)', which is required by gem 'puppet', in any of the sources.

**Comment by jpogran** [comment]
Try ` bundle install --without system_tests` instead. That will skip all of the beaker gems which aren't needed when building types

**Comment by jpogran** [comment]
This is resolved as per #271

**Comment by nealpeters86** [comment]
jpogran, worked. Thank you!
