### ISSUE TITLE
No Repofile to edit 

### ISSUE THREAD

**Issue by KosherSalt** [puppetlabs/puppetlabs-dsc#70]
In README_BUILD.md, it says to modify the Repofile to add your custom resources. However, that file doesn't exist in the current branch. I was able to find it in an older branch. I noticed that dsc.rake contains a variable pointing to the DSC resources on the PowerShell github account.

`dsc_repo                   = 'https://github.com/PowerShell/DscResources.git'`

Should we modify this variable instead of Repofile?

**Comment by ferventcoder** [comment]
We just removed that file. I think we need to update the readme.

**Comment by ferventcoder** [comment]
The quickest you can do currently:

* Start with a non-Windows box (we inherited this, but I think we all are moving towards getting it to work on a Windows machine, charlock_holmes gem is the culprit)
* Switch to ruby 1.9.3 (or 1.8.7)
* `bundle install --without system_tests`
* `bundle exec rake dsc:build`

**Comment by ferventcoder** [comment]
Adding custom resources is just making sure they are in the import folder prior to build.

**Comment by ferventcoder** [comment]
I created a ticket at https://tickets.puppetlabs.com/browse/MODULES-2799 to track this. Please subscribe and follow there. Thanks!
