### ISSUE TITLE
Error when running "bundle exec rake" to regenerate resource types

### ISSUE THREAD

**Issue by paulchernoch** [puppetlabs/puppetlabs-dsc#8]
I am attempting to regenerate all the resource types, in preparation for generating puppet wrapper resources for some new community DSC resources. The first two steps in the docs executed fine, but the third step fails:

1. gem install bundler
2. bundle install
3. bundle exec rake

It reports that this file could not be found: **pshorg-c-web-administration.psd1**

I tried to run through all this on Windows, but could never get charlock_holmes to build. Thus I am doing this on **Ubuntu 14**.

Here is the trace:

open /etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/import/dsc_resource_modules/pshorg-c-web-administration/DSCResources/PSHOrg_cWebsite/PSHOrg_cWebsite.schema.mof [pragma]
rake aborted!
module manifest /etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/import/dsc_resource_modules/pshorg-c-web-administration/pshorg-c-web-administration.psd1 not found
/etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/build/dsc/resource.rb:102:in `ps_module'
(erb):57:in `block (2 levels) in build_dsc_types'
/opt/puppet/lib/ruby/1.9.1/erb.rb:838:in `eval'
/opt/puppet/lib/ruby/1.9.1/erb.rb:838:in `result'
/etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/build/dsc/manager.rb:120:in `block (2 levels) in build_dsc_types'
/etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/build/dsc/manager.rb:119:in `open'
/etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/build/dsc/manager.rb:119:in `block in build_dsc_types'
/etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/build/dsc/manager.rb:113:in `each'
/etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/build/dsc/manager.rb:113:in `build_dsc_types'
/etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/build/dsc.rake:69:in `block (3 levels) in <top (required)>'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/etc/puppetconfig_tfs/3.7/environments/production/modules/puppet_forge/dsc/build/dsc.rake:8:in `block (2 levels) in <top (required)>'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/puppet/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/opt/puppet/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/opt/puppet/lib/ruby/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in `<main>'
Tasks: TOP => default => dsc:build

**Comment by ferventcoder** [comment]
I have fixes in my PR https://github.com/msutter/puppet-dsc/pull/5/commits (look at the first commit)

**Comment by Iristyle** [comment]
Closing this issue since that code has been merged to master.
